apiVersion: v1
kind: Pod
metadata:
  name: pod-with-pvc-static
  labels:
    Project: Expense
    division: Finance
spec:
  containers:
    - name: app
      image: nginx
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: my-storage # must match the volume name defined below to link (container & volume)
  volumes:
    - name: my-storage
      persistentVolumeClaim:
        claimName: my-pvc-static # must match your PVC name
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1c
    # Ensure the Pod is scheduled on a node which has
    # access to the EBS volume (PV) in the same availability zone.
