apiVersion: v1
kind: Pod
metadata:
  name: my-pod-secret
spec:
  containers:
    - name: my-container-secret
      image: nginx:1.14.2
      volumeMounts:
        - name: secret-volume # name of the volume defined below to link (container & volume)
          mountPath: "/tmp/secret-volume"
          readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: my-secret
