apiVersion: v1
kind: Pod
metadata:
  name: my-pod-secret
spec:
  containers:
    - name: my-container-secret
      image: nginx:1.14.2
      volumesMounts: #mount the secret as a volume for dynamic updates
        - name: secret-volume-mount
          mountPath: "/tmp/secret-volume" #the path where the secret will be mounted inside the container
          readOnly: true #make the volume read-only to prevent modifications
  volumes:
    - name: secret-volume-mount
      secret:
        secretName: my-secret
