apiVersion: v1
kind: Service
metadata:
  name: murali-cluster-ip-service
spec:
  selector: # selects the Pods that will be targeted by this Service.
    project: expense
    division: finance
  ports:
    - protocol: TCP
      port: 80 # Service port
      targetPort: 80 # Port on the Pod where the application is running

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx1
  labels: # labels are used to identify and group Pods. The Service uses these labels to select the Pods it will route traffic to.
    project: expense
    division: finance
spec:
  containers:
    - name: nginx
      image: nginx:stable

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  labels:
    project: expense
    division: finance
spec:
  containers:
    - name: nginx
      image: nginx:stable
