apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      Project: Expense
      division: Finance
  template: # This is the Pod template, will create Pods with these specifications
    metadata:
      labels:
        Project: Expense
        division: Finance
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
