apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      Project: Expense
      division: Finance

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-demo
  labels:
    Project: Expense
    division: Finance
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
