apiVersion: v1
kind: Service
metadata:
  name: murali-load-balancer-service
spec:
  type: LoadBalancer
  selector:
    Project: Expense
    division: Finance
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
