#Headless service
apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: expense
spec:
  clusterIP: None # this makes it headless service
  selector:
    app: mysql
    project: expense
  ports:
    - protocol: TCP
      port: 3306 # service port
      targetPort: 3306
---
# StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    matchLabels:
      app: mysql
      project: expense
  serviceName: "mysql-headless" #Headless service name
  replicas: 2
  minReadySeconds: 10 # time to wait before marking a pod as ready, default is 0 seconds
  template:
    metadata:
      labels:
        app: mysql
        project: expense
    spec:
      terminationGracePeriodSeconds: 10 # time to wait before forcefully terminating a pod, default is 30 seconds
      containers:
        - name: mysql
          image: mysql:5.7
          volumeMounts:
            - name: mysql
              mountPath: /var/lib/mysql
  # Instead of creating a PVC resource, you can directly provide in statefulset
  volumeClaimTemplates:
    - metadata:
        name: mysql
        namespace: expense
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "fast-storage"
        resources:
          requests:
            storage: 1Gi
