apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc-static
spec:
  resources:
    requests:
      storage: 5Gi # The amount of storage requested
  accessModes:
    - ReadWriteOnce # Must match the PV's access mode, this is mandatory.
  volumeName: my-pv-static # bind PVC to the specific PV named "my-pv-static"
