apiVersion: v1
kind: Service
metadata:
  name: murali-cluster-ip-service
spec:
  selector:
    Project: Expense
    divison: Finance
  ports:
    - protocol: TCP
      port: 80 # Service port
      targetPort: 80 # Port on the Pod where the application is running

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx1
  labels:
    Project: Expense
    divison: Finance
spec:
  containers:
    - name: nginx
      image: nginx:stable

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  labels:
    Project: Expense
    divison: Finance
spec:
  containers:
    - name: nginx
      image: nginx:stable
