apiVersion: v1
kind: Pod
metadata:
  name: webserver0
  labels:
    app: webserver-store
spec:
  containers:
    - name: webserver0
      image: nginx:1.14.2

---
apiVersion: v1
kind: Pod
metadata:
  name: webserver1
  labels:
    app: webserver-store
spec:
  containers:
    - name: webserver1
      image: nginx:1.14.2
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - webserver-store
          topologyKey: "kubernetes.io/hostname"
#"kubernetes.io/hostname" → same node pod will be scheduled
#"topology.kubernetes.io/zone" → same availability zone
#"topology.kubernetes.io/region" → same region
