apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc-dynamic
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: fast-storage
  #name of the StorageClass to use for dynamic provisioning, must match the name defined in 0.storage-class.yaml
