apiVersion: v1
kind: Pod
metadata:
  name: pod-with-pvc-dynamic
  labels:
    Project: Expense
    division: Finance
spec:
  containers:
    - name: app
      image: nginx
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: my-storage
  volumes:
    - name: my-storage
      persistentVolumeClaim:
        claimName: my-pvc-dynamic
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1c
