apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::890742589086:role/eksctl-Murali-k8s-cluster-nodegrou-NodeInstanceRole-1uzGE3Q8VyBZ
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::890742589086:user/muralixy
      username: muralixy
      groups:
        - system:masters
kind: ConfigMap
metadata:
  creationTimestamp: "2026-04-02T09:04:12Z"
  name: aws-auth
  namespace: kube-system
  uid: 21bdfcf7-f3bc-441a-96ef-4de79f6e3dbd
