apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: calc-trainee-role
rules:
  - apiGroups: [""] # indicates the core API group
    resources: ["*"] # * - means all resources or we can specify (pod,svc..)
    verbs: ["get", "watch", "list"] #Action they can take
