apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: Dev-Role-Binding-K8
  namespace: dev #restrict to dev namespace
subjects:
  - kind: Group
    name: Developer-Group-k8 # 👈 must match EKS Access Entry
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: Dev-Role-K8 # 👈 must match Role name in role.yaml
  apiGroup: rbac.authorization.k8s.io
